name: Build and publish Docker image

on:
  push:
    branches: [main] # or 'master' if that's your default branch

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # needed to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # or "./docker" if Dockerfile is in a subfolder
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ghdl-gtkwave:latest
